os: osx
osx_image: xcode9.3
language: swift

cache:
  - bundler

before_install:
  - bundle install

script:
  - bundle exec fastlane scan

notifications:
  email:
    recipients:
      - fantasy0404@gmail.com
      - jotshing@gmail.com
